# Generated by Django 5.2.8 on 2026-01-07 01:21

from django.db import migrations


def populate_categories_tags(apps, schema_editor):
	Category = apps.get_model("hoagiemail", "Category")
	Tag = apps.get_model("hoagiemail", "Tag")

	# Example categories and tags
	categories_tags = {
		"Anything": ["Announcement", "Opportunity", "Request"],
		"Student Sale": ["Accessories", "Clothing", "Tech", "Furniture", "School", "Tickets", "Other"],
		"Lost & Found": ["Lost", "Found"],
	}

	for category_name, tag_names in categories_tags.items():
		category, created = Category.objects.get_or_create(name=category_name)
		for tag_name in tag_names:
			Tag.objects.get_or_create(name=tag_name, category=category)


class Migration(migrations.Migration):
	dependencies = [
		("hoagiemail", "0001_initial"),
	]

	operations = [
		migrations.RunPython(populate_categories_tags),
	]
