# Generated by Django 6.0.1 on 2026-02-12 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemail', '0003_userlimits'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userlimits',
            table='UserLimits',
        ),
    ]
